Home:
    path: /
    controller: App\Controller\HomeController::index

Destination:
    path: /Partenaires
    controller: App\Controller\DestinationController::index

Jouet:
    path: /Jouets
    controller: App\Controller\JouetController::index